#!/usr/bin/env node

const chalk = require("chalk");
const fs = require("fs");
const { exit } = require("process");
const shell = require("shelljs");
const PackageJSON = require('../../lib/package-json');

function LIB(args) {
  const BUILD_ENV = args.env || 'production';
  const currentProject = PackageJSON();

  console.log(chalk.white(`📦 Packaging Library ${currentProject.name}`));
  console.log(chalk.yellow('Environment: '), BUILD_ENV);

  // # Cleanup
  console.log(chalk.green('🧹 Cleaning up'));
  [
    // Nothing to remove
  ].forEach(dir => {
    if (fs.existsSync(dir)) {
      console.log(chalk.gray(`Removing ${dir}`));
      shell.rm('-rf', dir);
    }
  })

  console.log(chalk.green('🏗  Genenrating Build'));
  let x = shell.exec('npm run build');

  if (x.code === 0) {
    console.log(chalk.gray(`Build Created. Ready to publish to NPM.`));
  } else {
    console.log(chalk.red('Build Failure'));
    exit(x.code);
  }

  // Releaseing a version and publishing a new verison to NPM (Artifactory)
  console.log(chalk.green('\n📢 Publishing a release'));
  shell.exec('npm run release');
  
  return ;
}

module.exports = LIB;