#!/usr/bin/env node

const chalk = require('chalk');
const fs = require('fs');
const shell = require('shelljs');
const PackageJSON = require('../../lib/package-json');
const GenerateVersion = require('../../lib/generate-version');
const path = require('path');
const { exit } = process;

function WEB(args) {
  // PACKAGE_PATH="build"
  const PACKAGE_PATH = args.packagePath || 'build';
  const BUILD_ENV = args.env || 'production';
  const currentProject = PackageJSON();
  const WEB_PROJECT_STYLES = {
    gatsby: 'Gatsby Js',
    cra: 'Create React App',
    unknown: 'Unknown'
  };
  console.log(chalk.white(`📦 Packaging WebApp ${currentProject.name} into`), `./${PACKAGE_PATH}`);
  console.log(chalk.yellow('Environment: '), BUILD_ENV);
  const PROJECT_STYLE = currentProject.dependencies.gatsby ? 'gatsby' : currentProject.dependencies['react-scripts'] ? 'cra' : 'unknown';
  console.log(`Current Project Style: ${chalk.greenBright(WEB_PROJECT_STYLES[PROJECT_STYLE])}`);

  if (PROJECT_STYLE !== 'gatsby' || PROJECT_STYLE === 'unknown') {
    console.log(chalk.redBright('🚫 Cannot continue. Only Gatsby Projects are supported.'));
    exit(1);
  }

  // # Cleanup
  console.log(chalk.green('🧹 Cleaning up'));
  [
    PACKAGE_PATH,
    '.cache',
    'public',
    'build.zip'
  ].forEach(dir => {
    if (fs.existsSync(dir)) {
      console.log(chalk.gray(`Removing ${dir}`));
      shell.rm('-rf', dir);
    }
  });

  console.log(chalk.green('⚙️  Genenrating'), chalk.greenBright('version.json'));
  shell.mkdir('public');
  GenerateVersion('public/version.json', BUILD_ENV, 'numeropay.com');
  console.log(chalk.gray('version.json created at'), chalk.whiteBright(path.resolve('public/version.json')));

  console.log(chalk.green('🏗  Genenrating Build'));
  shell.exec('npm run build');

  console.log(chalk.green('🎁  Packaging artifact'));
  shell.mv('public', PACKAGE_PATH);

  // zip -r build.zip ./build/*
  const PWD = shell.pwd();
  shell.cd(PACKAGE_PATH);
  const ArtifactPath = path.resolve('../build.zip');
  console.log(`zip -r ${ArtifactPath} ./*`);
  shell.exec(`zip -r ${ArtifactPath} ./*`);
  shell.cd(PWD);
  console.log(chalk.gray('Artifact created at'), chalk.whiteBright(ArtifactPath));

  // Releaseing a version and publishing artifact to Github releases (Artifactory)
  console.log(chalk.green('\n📢 Publishing a release artifact'));
  shell.exec('npm run release');
  return;
}

module.exports = WEB;
