name: Publish Package

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.5
        with:
          node-version: 14
      - name: Setup and install dependencies
        run: |
          npm i pnpm -g
          pnpm install
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
  Publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [Verify]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.5
        with:
          node-version: 14
      - name: Package 📦
        run: |
          npm i pnpm -g
          pnpm install
          pnpm run build
      - name: Publish 🚀
        run: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
